In [12]:
import pandas as pd

data_path = './data/mimic/files/'

In [84]:
admissions = pd.read_csv(data_path + 'ADMISSIONS.csv')

transfers = pd.read_csv(data_path + 'TRANSFERS.csv')

In [93]:
admissions

,ROW_ID,SUBJECT_ID,HADM_ID,ADMITTIME,DISCHTIME,DEATHTIME,ADMISSION_TYPE,ADMISSION_LOCATION,DISCHARGE_LOCATION,INSURANCE,LANGUAGE,RELIGION,MARITAL_STATUS,ETHNICITY,EDREGTIME,EDOUTTIME,DIAGNOSIS,HOSPITAL_EXPIRE_FLAG,HAS_CHARTEVENTS_DATA,ICU_ADM
0,21,22,165315,2196-04-09 12:26:00,2196-04-10 15:54:00,NaN,EMERGENCY,EMERGENCY ROOM ADMIT,DISC-TRAN CANCER/CHLDRN H,Private,NaN,UNOBTAINABLE,MARRIED,WHITE,2196-04-09 10:06:00,2196-04-09 13:24:00,BENZODIAZEPINE OVERDOSE,0,1,False
1,22,23,152223,2153-09-03 07:15:00,2153-09-08 19:10:00,NaN,ELECTIVE,PHYS REFERRAL/NORMAL DELI,HOME HEALTH CARE,Medicare,NaN,CATHOLIC,MARRIED,WHITE,NaN,NaN,CORONARY ARTERY DISEASE\CORONARY ARTERY BYPASS...,0,1,False
2,23,23,124321,2157-10-18 19:34:00,2157-10-25 14:00:00,NaN,EMERGENCY,TRANSFER FROM HOSP/EXTRAM,HOME HEALTH CARE,Medicare,ENGL,CATHOLIC,MARRIED,WHITE,NaN,NaN,BRAIN MASS,0,1,True
3,24,24,161859,2139-06-06 16:14:00,2139-06-09 12:48:00,NaN,EMERGENCY,TRANSFER FROM HOSP/EXTRAM,HOME,Private,NaN,PROTESTANT QUAKER,SINGLE,WHITE,NaN,NaN,INTERIOR MYOCARDIAL INFARCTION,0,1,False
4,25,25,129635,2160-11-02 02:06:00,2160-11-05 14:55:00,NaN,EMERGENCY,EMERGENCY ROOM ADMIT,HOME,Private,NaN,UNOBTAINABLE,MARRIED,WHITE,2160-11-02 01:01:00,2160-11-02 04:27:00,ACUTE CORONARY SYNDROME,0,1,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58971,58594,98800,191113,2131-03-30 21:13:00,2131-04-02 15:02:00,NaN,EMERGENCY,CLINIC REFERRAL/PREMATURE,HOME,Private,ENGL,NOT SPECIFIED,SINGLE,WHITE,2131-03-30 19:44:00,2131-03-30 22:41:00,TRAUMA,0,1,False
58972,58595,98802,101071,2151-03-05 20:00:00,2151-03-06 09:10:00,2151-03-06 09:10:00,EMERGENCY,CLINIC REFERRAL/PREMATURE,DEAD/EXPIRED,Medicare,ENGL,CATHOLIC,WIDOWED,WHITE,2151-03-05 17:23:00,2151-03-05 21:06:00,SAH,1,1,False
58973,58596,98805,122631,2200-09-12 07:15:00,2200-09-20 12:08:00,NaN,ELECTIVE,PHYS REFERRAL/NORMAL DELI,HOME HEALTH CARE,Private,ENGL,NOT SPECIFIED,MARRIED,WHITE,NaN,NaN,RENAL CANCER/SDA,0,1,True
58974,58597,98813,170407,2128-11-11 02:29:00,2128-12-22 13:11:00,NaN,EMERGENCY,EMERGENCY ROOM ADMIT,SNF,Private,ENGL,CATHOLIC,MARRIED,WHITE,2128-11-10 23:48:00,2128-11-11 03:16:00,S/P FALL,0,0,False
58975,58598,98813,190264,2131-10-25 03:09:00,2131-10-26 17:44:00,NaN,EMERGENCY,CLINIC REFERRAL/PREMATURE,HOME,Private,ENGL,CATHOLIC,MARRIED,WHITE,2131-10-25 00:08:00,2131-10-25 04:35:00,INTRACRANIAL HEMORRHAGE,0,1,False

In [85]:
transfers = transfers.drop(transfers[transfers['EVENTTYPE'] != 'transfer'].index)
transfers = transfers.drop(transfers[transfers['ICUSTAY_ID'].isna()].index)

transfers = transfers.drop(transfers[transfers['CURR_CAREUNIT'] == 'CSRU'].index)
transfers = transfers.drop(transfers[transfers['CURR_CAREUNIT'] == 'NICU'].index)

In [86]:
transfers

,ROW_ID,SUBJECT_ID,HADM_ID,ICUSTAY_ID,DBSOURCE,EVENTTYPE,PREV_CAREUNIT,CURR_CAREUNIT,PREV_WARDID,CURR_WARDID,INTIME,OUTTIME,LOS
0,657,111,192123,254245.0,carevue,transfer,CCU,MICU,7.0,23.0,2142-04-29 15:27:11,2142-05-04 20:38:33,125.19
5,662,111,155897,249202.0,metavision,transfer,NaN,MICU,32.0,52.0,2144-07-01 06:28:29,2144-07-01 08:07:16,1.65
7,664,111,155897,249202.0,metavision,transfer,NaN,MICU,32.0,23.0,2144-07-01 08:13:51,2144-07-01 17:56:31,9.71
16,673,112,173177,251972.0,carevue,transfer,NaN,MICU,17.0,50.0,2196-09-28 00:30:29,2196-09-29 03:50:53,27.34
26,683,115,114585,232514.0,carevue,transfer,NaN,SICU,54.0,57.0,2194-10-17 13:22:28,2194-10-24 16:26:47,171.07
...,...,...,...,...,...,...,...,...,...,...,...,...,...
261868,258729,97689,126800,203408.0,metavision,transfer,NaN,CCU,3.0,7.0,2140-07-14 22:59:38,2140-07-15 21:18:16,22.31
261884,259663,98385,153384,283750.0,metavision,transfer,NaN,TSICU,36.0,14.0,2108-07-19 18:41:46,2108-07-20 21:43:43,27.03
261885,259664,98385,153384,283750.0,metavision,transfer,TSICU,TSICU,14.0,14.0,2108-07-20 21:43:43,2108-08-15 17:51:17,620.13
261887,259666,98385,153384,283750.0,metavision,transfer,NaN,TSICU,36.0,14.0,2108-08-16 10:41:25,2108-08-22 22:02:27,155.35
261893,259672,98385,195599,292167.0,metavision,transfer,NaN,SICU,49.0,33.0,2108-10-06 13:05:57,2108-10-11 17:00:31,123.91

In [87]:
icu_admissions = transfers['HADM_ID'].tolist()

def icu_admit(hadm_id):
    return (hadm_id in icu_admissions)

admissions['ICU_ADM'] = admissions.apply(lambda row: icu_admit(row['HADM_ID']),axis=1)

In [88]:
set(admissions["ICU_ADM"].tolist())

{False, True}

In [89]:
sum(admissions['ICU_ADM'].tolist())/len(admissions['ICU_ADM'].tolist())

0.37594953879544224

In [90]:
set(transfers['CURR_CAREUNIT'].tolist())

{'CCU', 'MICU', 'SICU', 'TSICU'}